### ISSUE TITLE
Sorting Admin Boundaries

### ISSUE THREAD

**Issue by janbur** [unicef/unicef-geospacial#12]
Perhaps would be nice to sort admin boundaries in the Admin interface using hierarchy, i.e. first level 0, than level 1, 2, and so on...

Currently admin level 0 shows in the middle of the table:
![image](https://user-images.githubusercontent.com/37516253/54709800-81dc4080-4b46-11e9-908b-037e8e1e569e.png)

**Comment by domdinicola** [comment]
are you sure the first item of the list has Mozambique has parent?

**Comment by janbur** [comment]
I think so. All admin boundaries above have Mozambique as a top parent. See also below (first record on the list should be Mozambique / country):

![image](https://user-images.githubusercontent.com/37516253/54775912-45c0e280-4c0f-11e9-99fc-177113358d6a.png)
